name = "seedr"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "seedr-analytics"
database_id = "51d143da-fb42-4a57-8493-c45695a3637c"
